version: "3.9"

networks:
  prt-videodownloader-net:
    name: prt-videodownloader-net

volumes:
  prt_videodownloader_db: {}

services:
  prt-videodownloader-api:
    container_name: prt-videodownloader-api
    image: prt-videodownloader-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - PRT_VIDEODOWNLOADER_VIDEODATAPATH=/opt/prt/prt-videodownloader/data
      - PRT_VIDEODOWNLOADER_SQLITEFILEPATH=/opt/prt/prt-videodownloader/db/prt-videodownloader.sqlite
      - PRT_VIDEODOWNLOADER_HTTPSBASEURL=https://prtlabs.teevity.com:9443/videodownloader/data
    volumes:
      # Shared data directory (host <-> both containers)
      - ${PRT_OPT_BASEPATH}/data:/opt/prt/prt-videodownloader/data:rw
      # Persist the SQLite DB within a named volume (optional)
      - prt_videodownloader_db:/opt/prt/prt-videodownloader/db
    ports:
      - "9480:8080"
    restart: unless-stopped
    networks:
      - prt-videodownloader-net

  prt-videodownloader-nginx:
    container_name: prt-videodownloader-nginx
    image: nginx:1.27-alpine
    depends_on:
      - prt-videodownloader-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PRT_OPT_BASEPATH}/certs/live/teevity.com:/etc/letsencrypt:ro
      - ${PRT_OPT_BASEPATH}/data:/opt/prt/prt-videodownloader/data:rw
      - ${PRT_VIDEODOWNLOAD_PROJECT}/openapi.json:/opt/prt/prt-videodownloader/openapi.json:rw
    ports:
      - "9443:443"
    restart: unless-stopped
    networks:
      - prt-videodownloader-net
